export type Seg = { t: string; c?: "accent" | "teal" | "amber" };
export type Row = { segs: Seg[] } | "div";

export const WIREFRAMES: Record<string, Row[]> = {
  "argent-android": [
    { segs: [{ t: "home" }] },
    "div",
    { segs: [{ t: "balance" }] },
    { segs: [{ t: "48,210.00" }] },
    "div",
    { segs: [{ t: "[ send ]     [ request ]" }] },
    "div",
    { segs: [{ t: "rent               " }, { t: "confirmed", c: "teal" }] },
    { segs: [{ t: "groceries          " }, { t: "confirmed", c: "teal" }] },
    { segs: [{ t: "to ravi            " }, { t: "pending", c: "amber" }] },
    { segs: [{ t: "no signal — queued, retrying with jitter" }] },
  ],
  "basis-kmp": [
    { segs: [{ t: "shared core (kotlin)" }] },
    "div",
    { segs: [{ t: "android  " }, { t: "-> ", c: "accent" }, { t: "compose ui" }] },
    { segs: [{ t: "ios      " }, { t: "-> ", c: "accent" }, { t: "swiftui ui" }] },
    "div",
    { segs: [{ t: "valuation · cost basis · allocation" }] },
    "div",
    { segs: [{ t: "tests  jvm " }, { t: "ok", c: "teal" }, { t: "   kotlin/native " }, { t: "ok", c: "teal" }] },
  ],
  "slate-ai": [
    { segs: [{ t: "> summarize my meeting notes" }] },
    { segs: [{ t: "routing: short lookup" }] },
    { segs: [{ t: "-> on-device (litert)  ", c: undefined }, { t: "40ms", c: "teal" }] },
    "div",
    { segs: [{ t: "> synthesize last quarter" }] },
    { segs: [{ t: "routing: needs deep context" }] },
    { segs: [{ t: "-> cloud escalation  ", c: undefined }, { t: "queued", c: "amber" }] },
    "div",
    { segs: [{ t: "rag: chunk -> embed -> retrieve  (12 tests)" }] },
  ],
  modulith: [
    { segs: [{ t: ":core            no deps" }] },
    { segs: [{ t: ":feature-a  ->   :core     ok", c: undefined }] },
    { segs: [{ t: ":feature-b  ->   :core     ok", c: undefined }] },
    { segs: [{ t: ":feature-b  ->   :feature-a   x" }] },
    "div",
    { segs: [{ t: "checkModuleGraph: illegal edge caught" }] },
    { segs: [{ t: "feature -> feature is not allowed" }] },
    "div",
    { segs: [{ t: "module build file: ~2 lines (convention)" }] },
  ],
};
